### ISSUE TITLE
Upgrade Kotlin to 1.5.20 or higher to allow use of Gradle 7.3

### ISSUE THREAD

**Issue by techouse** [mParticle/mparticle-flutter-sdk#33]
Hi,

I just attempted to build my Flutter app with Gradle 7.3 and was greeted with this error message

```
FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':mparticle_flutter_sdk' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Exception: Gradle task assembleDebug failed with exit code 1
```

Looks like the [`ext.kotlin_version`](https://github.com/mParticle/mparticle-flutter-sdk/blob/development/android/build.gradle#L5) will need to be upgraded to 1.5.20 or higher in order to allow the use of Gradle 7.3.

It compiles just fine with Gradle 7.2.2.

**Comment by rmi22186** [comment]
This has been published as version 1.0.2.  https://pub.dev/packages/mparticle_flutter_sdk

Thank you for your patience and help with this!  @techouse @johannsa
