### ISSUE TITLE
Location is missing from iOS flutter integration

### ISSUE THREAD

**Issue by theideasaler** [mParticle/mparticle-flutter-sdk#38]
Hi,
<img width="259" alt="image" src="https://github.com/mParticle/mparticle-flutter-sdk/assets/17869748/5f110796-377b-43c2-879a-50eaa73bb174">
I am trying to integrating mParticle flutter sdk into an iOS app.  Following the guides below: 
https://docs.mparticle.com/developers/sdk/flutter/getting-started/
https://docs.mparticle.com/developers/sdk/ios/initialization/

mParticle integrations have also been implemented with these guides for Android and web: https://docs.mparticle.com/developers/sdk/android/initialization/, https://docs.mparticle.com/developers/sdk/web/initialization/

The events are sent to mParticle dashboard without a problem in all platforms.

However, I have observed one thing different between iOS and Android/web is that the location in the Dashboard's Data(Live Stream) is missing from the event sent from iOS, while the Android & website have it by default.

Please guide if there is any configuration needed to include location in the event for iOS?

**Comment by theideasaler** [comment]
please find the minimum reproducible flutter example project: https://github.com/theideasaler/ios_mparticle_poc

**Comment by theideasaler** [comment]
New updates: the Custom Events are not received in Live Stream for iOS released app but Custom Events from Android are received in Live Stream successfully.

**Comment by rmi22186** [comment]
This has been routed via a support ticket in Zendesk (#12489).  Closing this ticket here as ZD is the appropriate way to get support.
